### ISSUE TITLE
[Meta] React kit 5.0 - based on Bootstrap Italia 2

### ISSUE THREAD

**Issue by dej611** [italia/design-react-kit#890]
This is a meta issue for the next version of the kit, which will be compatible with the new Bootstrap Italia 2 version.

# Tasks

* [ ] Create branch next from master (will become main in the next major release).
* [ ]Force the update (on the next branch) of all the dependencies, including Bootstrap Italia 2 and the latest Reactstrap, both based on Bootstrap 5.
* [ ] Add a label next to issues.
* Verify, and update CI and GitHub Actions.
  * Add new action for the `next` branch to deploy alpha versions of the kit
* Start opening, if needed, dedicated issues for next branch. For each components we will have to:
  * [] Verify and update, markup and classes of the resulting DOM template, compared to Bootstrap Italia 2
    * Check reactstrap upgrading guide: https://reactstrap.github.io/?path=/docs/home-upgrading--page
    * Check Bootstrap 5 upgrading guide: https://getbootstrap.com/docs/5.1/migration/#components 
    * [ ] Check the rendering of the component (CSS application including spacing, dimensions, typography, ...), compared to Bootstrap Italia and the new UI kit
    * [ ] Check the behavior of the component (JavaScript, user interaction, states, keyboard interaction for accessibility, ...), compared to Bootstrap Italia 2
    * [ ] Verify the accessibility of the component, including automatic tests and manual evaluations by a11y experts, if possible
    * [ ] Evaluate the need to supplement the component storybook documentation with more detailed information.

Work already in progress that can be tracked here: #885

**Comment by gcapuanoRegione** [comment]
Buonasera,

è prevista una data di rilascio? Giusto per avere una idea di quando sarà disponibile per un utilizzo in produzione. Grazie

**Comment by dej611** [comment]
@gcapuanoRegione non esiste una data di rilascio al momento.
Puoi seguire il progresso dello sviluppo su questa PR #885

**Comment by federico-ntr** [comment]
Bootstrap Italia has a [Torna Indietro](https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/torna-indietro/) entry under "Menu di navigazione". It uses a bootstrap feature to go back, but we shouldn't use a vanilla javascript solution as most people probably use `react-router` to manage navigation.

Should we just ignore that page or is it worth creating one with an example using `react-router`'s `useNavigate` hook?

**Comment by Virtute90** [comment]
> ### Work progress React Kit bts-italia 2.3.4
> **Implemented**
> 
> * Accordions
> * Steppers
> 
> Bug fixed migrate by BI 1 to 2 #926 #929 #931 #933 #935 #941 #943 #944 #945 #949 #951
> 
> **TODO**
> 
> * Alert [[FEATURE] Alert component #905](https://github.com/italia/design-react-kit/issues/905)
> * Card [[FEATURE] Card component #906](https://github.com/italia/design-react-kit/issues/906)
> * Breadcrumbs [[FEATURE] Breadcrumbs component #907](https://github.com/italia/design-react-kit/issues/907)
> * Button [[FEATURE] Button component #908](https://github.com/italia/design-react-kit/issues/908)
> * Collapse [[FEATURE] Collapse component #909](https://github.com/italia/design-react-kit/issues/909)
> * Input [[FEATURE] Component Input #911](https://github.com/italia/design-react-kit/issues/911)
> * Numeric Input [[FEATURE] Numeric Input component #912](https://github.com/italia/design-react-kit/issues/912)
> * Checkbox [[FEATURE] Component checkbox #913](https://github.com/italia/design-react-kit/issues/913)
> * Select [[FEATURE] Component Select #914](https://github.com/italia/design-react-kit/issues/914)
> * Radio button [[FEATURE] Component Radio Button #916](https://github.com/italia/design-react-kit/issues/916)
> * Autocomplete [[FEATURE] Autcomplete component #917](https://github.com/italia/design-react-kit/issues/917)
> * BackToTop [[FEATURE] Component Back to top #954](https://github.com/italia/design-react-kit/issues/954)
> * Grids [Missing Documentation: Components Grids #789](https://github.com/italia/design-react-kit/issues/789)
> * Responsive Image [Missing Documentation: Component ResponsiveImage #788](https://github.com/italia/design-react-kit/issues/788)
> * Pagination [Missing documentation: Componenti - Paginazione #777](https://github.com/italia/design-react-kit/issues/777)
> * Tabs [Missing documentation: Componenti - Tab #776](https://github.com/italia/design-react-kit/issues/776)
> * Steppers documentations [[FEATURE] Add Steppers documentation #773](https://github.com/italia/design-react-kit/issues/773)
> * Upload [[FEATURE] Implement Upload component as in BI #665](https://github.com/italia/design-react-kit/issues/665)
> * Add Password strength meter component/feature [[FEATURE] Add Password strength meter component/feature #641](https://github.com/italia/design-react-kit/issues/641)
> * Transform [[FEATURE] Transfer component #639](https://github.com/italia/design-react-kit/issues/639)
> * Datepicker Input [[FEATURE] Datepicker input component #638](https://github.com/italia/design-react-kit/issues/638)
> * Carousel [[FEATURE] Carousel component #395](https://github.com/italia/design-react-kit/issues/395)

Is it possible to convert the TODO list into a checklist to understand what is missing for the next release?

**Comment by astagi** [comment]
@Virtute90 it is! we moved `next` branch to `main` and we'll open specific issues of missing components, bugs and enhancements next week. Stay tuned 🙌

**Comment by astagi** [comment]
> Buonasera,
> 
> è prevista una data di rilascio? Giusto per avere una idea di quando sarà disponibile per un utilizzo in produzione. Grazie

@gcapuanoRegione adesso possiamo dirlo con più tranquillità, data di rilascio 5.0.0 entro il Q1 di quest'anno.
